#################################################
############### API LIBRERÍA ####################
#################################################


#################################################
# AGREGAR LIBRO
#################################################

POST http://localhost:8080/libros
Content-Type: application/json

{
  "Nombre": "Cien años de soledads",
  "Genero": "ayuwoki",
  "Autor": "Gabriel Garcías Márquez",
  "fecha_recepcion": "2024-06-01",
  "cantidad_copias": 5,
  "edad_sugerida": 14,
  "editorial": "Sudamericana",
  "precio": 18500,
  "estado": 1
}


#################################################
# GENERAR COPIA DE UN LIBRO
#################################################

POST http://localhost:8080/libros/copy
Content-Type: application/json

{
  "id": 1,
  "codBarra": "12212212122"
}


#################################################
# AGREGAR USUARIO
#################################################

POST http://localhost:8080/users
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "rut": "12345678-8",
  "direccion": "Av. Siempre Viva 123"
}


#################################################
# ACTUALIZAR PRECIO DE UN LIBRO
#################################################

PATCH http://localhost:8080/libros/1
Content-Type: application/json

{
  "precio": 41
}


#################################################
# DESHABILITAR COPIA DE UN LIBRO
#################################################

PATCH http://localhost:8080/libros/disable/1
Content-Type: application/json



#################################################
# DESHABILITAR USUARIO
#################################################
PATCH http://localhost:8080/users/disable/1
Content-Type: application/json


#################################################
# VER TODOS LOS LIBROS
#################################################

GET http://localhost:8080/libros
Content-Type: application/json


#################################################
# GENERAR TRANSACCION
#################################################
POST http://localhost:8080/transaction
Content-Type: application/json

{
  "Trabajadorid": 1,
  "Usuarioid": 1,
  "Copia_libroid": 4,
  "es_venta": true,
  "es_prestamo": false
}
#################################################
# Obtener detalles de una transacción
##############################################
get http://localhost:8080/transaction/details
Content-Type: application/json

{
  "id": 1,
  "date": "2024-06-01"
}
#################################################
############### API LIBRERÍA ####################
#################################################

BASE URL: http://localhost:8080

#################################################
# LIBROS
#################################################

### Agregar libro
POST http://localhost:8080/libros
Content-Type: application/json

{
  "Nombre": "Cien años de soledad",
  "Genero": "Realismo",
  "Autor": "Gabriel García Márquez",
  "fecha_recepcion": "2024-06-01",
  "cantidad_copias": 5,
  "edad_sugerida": 14,
  "editorial": "Sudamericana",
  "precio": 18500,
  "estado": 1
}

### Generar copia de un libro
POST http://localhost:8080/libros/copy
Content-Type: application/json

{
  "id": 1,
  "codBarra": "12212212122"
}

### Actualizar precio de un libro
PATCH http://localhost:8080/libros/1
Content-Type: application/json

{
  "precio": 20000
}

### Deshabilitar copia de libro
PATCH http://localhost:8080/libros/disable/1
Content-Type: application/json


### Actualizar stock (incrementar cantidad)
PATCH http://localhost:8080/libros/updateStock/1
Content-Type: application/json

{
  "cantidad": 3
}

### Ver todos los libros
GET http://localhost:8080/libros
Content-Type: application/json


### Libros recientes
GET http://localhost:8080/libros/recent
Content-Type: application/json


#################################################
# USUARIOS
#################################################

### Agregar usuario (simple)
POST http://localhost:8080/users
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "rut": "12345678-8",
  "direccion": "Av. Siempre Viva 123",
  "email": "juan@correo.com",
  "password": "123456"
}

### Registrar usuario (registro alternativo)
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "nombre": "María López",
  "rut": "98765432-1",
  "direccion": "Calle Falsa 456",
  "estado": 1
}

### Registrar trabajador
POST http://localhost:8080/users/trabajador/registrarTrabajador
Content-Type: application/json

{
  "nombre": "Ana Gómez",
  "rut": "11111111-1",
  "direccion": "Av. Central 10",
  "email": "ana@gremio.com",
  "password": "trabajador123"
}

### Deshabilitar usuario
PATCH http://localhost:8080/users/disable/1
Content-Type: application/json


### Login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "juan@correo.com",
  "password": "123456"
}

### Listar usuarios
GET http://localhost:8080/users
Content-Type: application/json


### Usuarios y trabajadores
GET http://localhost:8080/users/users-workers
Content-Type: application/json


### Usuarios con préstamos
GET http://localhost:8080/users/loan
Content-Type: application/json


### Listar bibliotecarias
GET http://localhost:8080/users/librains
Content-Type: application/json


#################################################
# TRANSACCIONES
#################################################

### Generar transacción (préstamo/venta)
POST http://localhost:8080/transaction
Content-Type: application/json

{
  "Trabajadorid": 1,
  "Usuarioid": 1,
  "Copia_libroid": 4,
  "es_venta": true,
  "es_prestamo": false
}

### Obtener detalles de una transacción (body validated)
GET http://localhost:8080/transaction/details
Content-Type: application/json

{
  "id": 1,
  "date": "2024-06-01"
}

### Obtener reporte categoría Comedia
GET http://localhost:8080/transaction/comedia
Content-Type: application/json


### Ventas en el año actual
GET http://localhost:8080/transaction/ventas
Content-Type: application/json

