
// return executeQuery(query, [nombre, autor, fechaRecepcion,0,edadSugerida, editorial,precio,"disponible"]);



###post para agregar un libro
POST http://localhost:8080/Libros
Content-Type: application/json

{
  "nombre": "El señor de los anillos2",
  "autor": "J.R.R. Tolkien",
  "fechaRecepcion": "2024-06-01",
  "edadSugerida": 12,
  "editorial": "Minotauro",
  "precio": 25
}
###post para generar una copia de un libro
POST http://localhost:8080/Libros/1
Content-Type: application/json

{
  "codBarra": "1234567890125"
}

###post para agregar un usuario
POST http://localhost:8080/users
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "edad": 25,
  "rut": "12345678-9",
  "direccion": "Av. Siempre Viva 123"
}
###patch para actualizar el precio de un libro
PATCH http://localhost:8080/Libros
Content-Type: application/json

{
  "id": 1,
  "precio": 30
}
