#################################################
############### API LIBRERÍA ####################
#################################################


#################################################
# AGREGAR LIBRO
#################################################

POST http://localhost:8080/libros
Content-Type: application/json

{
  "nombre": "Cien años de soledad",
  "genero": 1,
  "autor": "Gabriel García Márquez",
  "fechaRecepcion": "2024-06-01",
  "cantCopias": 5,
  "edadSugerida": 14,
  "editorial": "Sudamericana",
  "precio": 18500,
  "estado": 1
}


#################################################
# GENERAR COPIA DE UN LIBRO
#################################################

POST http://localhost:8080/libros/copy
Content-Type: application/json

{
  "id": 1,
  "codBarra": "12213123"
}


#################################################
# AGREGAR USUARIO
#################################################

POST http://localhost:8080/users
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "edad": 25,
  "rut": "12345678-9",
  "direccion": "Av. Siempre Viva 123"
}


#################################################
# ACTUALIZAR PRECIO DE UN LIBRO
#################################################

PATCH http://localhost:8080/libros/price
Content-Type: application/json

{
  "id": 1,
  "precio": 41
}


#################################################
# DESHABILITAR COPIA DE UN LIBRO
#################################################

PATCH http://localhost:8080/libros/disable
Content-Type: application/json

{
  "id": 1
}

#################################################
# DESHABILITAR USUARIO
#################################################
PATCH http://localhost:8080/users/disable
Content-Type: application/json

{
  "rut": "12345678-9"
}